'use strict';
window.collections = [];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const header=$('#header');
addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>80);$('.mobile-bottom').classList.toggle('shown',scrollY>600)},{passive:true});
function showDialog(dialog){dialog.showModal();document.body.classList.add('modal-open')}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(d.id==='mobile-menu')$('.menu-toggle').setAttribute('aria-expanded','false')});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
document.addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(b)b.closest('dialog').close()});
$('.menu-toggle').onclick=()=>{showDialog($('#mobile-menu'));$('.menu-toggle').setAttribute('aria-expanded','true')};
$$('#mobile-menu a').forEach(a=>a.onclick=()=>$('#mobile-menu').close());
const models=[
{id:'senso',name:'SENSO 488',tag:'СВЕТ И ПРОСТОТА',finish:'Матовый белый',description:'Светлые матовые фасады и выразительные древесные детали. Спокойная кухня, открытая для жизни.',code:'488 · Premium honed white',path:'natural-scandi/senso-488'},
{id:'natura',name:'NATURA 744',tag:'ТЕПЛО ПРИРОДЫ',finish:'Фактура дуба Montreal',description:'Тёплый характер древесной фактуры и чистая геометрия. Фасад с декором дуба Montreal — не массив дерева.',code:'744 · Oak Montreal reproduction',path:'natural-scandi/natura-744'},
{id:'riva',name:'RIVA 842',tag:'МЯГКАЯ ГЕОМЕТРИЯ',finish:'Песочная фактура бетона',description:'Сдержанный песочный оттенок с декором бетона. Архитектурное решение для современного пространства.',code:'842 · Concrete sand reproduction',path:'modern-kitchens/riva-842'},
{id:'slate',name:'SENSO 491',tag:'ВЫРАЗИТЕЛЬНЫЙ КОНТРАСТ',finish:'Матовый сланцевый серый',description:'Глубокий серый оттенок и ясные линии. Выразительная основа для кухни с собственным характером.',code:'491 · Premium honed slate grey',path:'designer-kitchens/senso-491'},
{id:'easy',name:'EASYTOUCH 969',tag:'ЕСТЕСТВЕННОЕ РАВНОВЕСИЕ',finish:'Ультраматовый песочный',description:'Мягкий песочный цвет объединяет кухню с жилым пространством. Тёплая нейтральная палитра для цельного интерьера.',code:'969 · Sand ultra matt',path:'designer-kitchens/easytouch-969'}
];
window.collections=models;
const track=$('#collection-track');
track.innerHTML=models.map(m=>`<button class="collection-card" data-model="${m.id}" aria-label="Подробнее о ${m.name}"><div class="photo"><img src="${m.id}.webp" alt="Кухня Nobilia ${m.name}, ${m.finish.toLowerCase()}" width="1000" height="730" loading="lazy"><span class="photo-tag">${m.tag}</span></div><div class="card-info"><div><h3>${m.name}</h3><p>${m.finish}</p></div><span class="detail">Подробнее <span>↗</span></span></div></button>`).join('');
let activeIndex=0;
function updateCarousel(){const cards=$$('.collection-card');const left=track.getBoundingClientRect().left+parseFloat(getComputedStyle(track).paddingLeft);activeIndex=cards.reduce((best,c,i)=>Math.abs(c.getBoundingClientRect().left-left)<Math.abs(cards[best].getBoundingClientRect().left-left)?i:best,0);$('#collection-counter').textContent=`${String(activeIndex+1).padStart(2,'0')} / 05`;$('#prev').disabled=track.scrollLeft<5;$('#next').disabled=track.scrollLeft+track.clientWidth>=track.scrollWidth-5}
track.addEventListener('scroll',updateCarousel,{passive:true});addEventListener('resize',updateCarousel);updateCarousel();
function moveCarousel(dir){track.scrollBy({left:dir*($('.collection-card').getBoundingClientRect().width+parseFloat(getComputedStyle(track).gap)),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
$('#prev').onclick=()=>moveCarousel(-1);$('#next').onclick=()=>moveCarousel(1);
const state={model:null,mood:null,source:'contact',type:'estimate',interest:null};
let lastGalleryTrigger=null;
function openGallery(id,trigger){const m=models.find(x=>x.id===id);if(!m)throw Error('Unknown collection');lastGalleryTrigger=trigger||lastGalleryTrigger;$('#gallery-content').innerHTML=`<img class="gallery-image" src="${m.id}.webp" alt="Кухня Nobilia ${m.name}"><div class="gallery-body"><p class="eyebrow">КОЛЛЕКЦИЯ NOBILIA</p><h2 id="gallery-title">${m.name}</h2><p>${m.description}</p><p><strong>Фасад:</strong> ${m.code}</p><div class="gallery-thumbnails" role="group" aria-label="Фотографии ${m.name}">${['','-1','-3'].map((suffix,i)=>`<button data-gallery-src="${m.id}${suffix}.webp" aria-label="Фото ${i+1}" aria-pressed="${i===0}"><img src="${m.id}${suffix}.webp" alt="Ракурс ${i+1}" width="90" height="55"></button>`).join('')}</div><button class="button" data-gallery-estimate="${m.id}">Рассчитать такую кухню <span>↗</span></button><p class="gallery-source">Фото и пример комплектации: <a href="https://www.nobilia.de/en/products/kitchens/${m.path}/" target="_blank" rel="noopener">Nobilia</a>. Это коллекция производителя, не реализованный проект салона. Комплектация определяется индивидуально.</p><p id="gallery-status" role="status" class="small"></p></div>`;showDialog($('#gallery'));}
$('#gallery').addEventListener('close',()=>{if(lastGalleryTrigger?.isConnected)lastGalleryTrigger.focus({preventScroll:true})});
let imageRequest=0;
async function swapImage(target,src,status){const token=++imageRequest;status.textContent='Загружаем фотографию…';return new Promise(resolve=>{const image=new Image();image.onload=()=>{if(token!==imageRequest)return resolve(false);target.src=src;status.textContent='';resolve(true)};image.onerror=()=>{if(token!==imageRequest)return resolve(false);status.replaceChildren(document.createTextNode('Не удалось загрузить фотографию. '));const retry=document.createElement('button');retry.className='plain';retry.textContent='Повторить';retry.onclick=()=>swapImage(target,src,status);status.append(retry);resolve(false)};image.src=src})}
const moods={light:{title:'Светлое и спокойное',label:'Светлое',model:'senso',desc:'Мягкий белый, естественный свет и ощущение простора. Простая основа для жизни, наполненной деталями.'},warm:{title:'Тёплое и естественное',label:'Тёплое',model:'natura',desc:'Выразительная древесная фактура и тёплые оттенки. Пространство, в котором хочется задержаться.'},contrast:{title:'Глубокое и выразительное',label:'Контрастное',model:'slate',desc:'Матовый серый и выразительная геометрия. Спокойный контраст, который раскрывает архитектуру кухни.'}};
async function selectMood(key){const m=moods[key];if(!m)throw Error('Неизвестное направление');const model=models.find(x=>x.id===m.model);const ok=await swapImage($('#mood-image'),`${m.model}.webp`,$('#mood-status'));if(!ok)return{status:'image_error'};state.mood=key;$('#mood-image').alt=`${m.label} направление — Nobilia ${model.name}`;$('#mood-title').textContent=m.title;$('#mood-desc').textContent=m.desc;$('#mood-model').textContent=model.name;$('#mood-summary').textContent=`${m.label} направление · ${model.name}`;$$('[data-mood]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mood===key)));syncContext();return{status:'selected',mood:key,collection:model.name}}
const tabText={front:'Матовые поверхности, древесные и каменные фактуры. Сравним образцы при разном освещении и найдём сочетание для вашего интерьера.',plan:'Линейная кухня, угловая композиция или остров. Продумываем рабочие зоны, проходы и расположение техники с учётом размеров вашего помещения.',storage:'Порядок начинается с удобного хранения. Подберём расположение ящиков и шкафов, а наполнение согласуем с вашими привычками и комплектацией.'};
function setTab(button){$$('[data-tab]').forEach(b=>{const selected=b===button;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1});$('#material-tabpanel').setAttribute('aria-labelledby',button.id);$('#material-tabpanel').innerHTML=`<p>${tabText[button.dataset.tab]}</p>`}
$$('[data-tab]').forEach((button,i)=>{button.onclick=()=>setTab(button);button.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const buttons=$$('[data-tab]');const index=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;buttons[index].focus();setTab(buttons[index])}}});
function formMarkup(id){return `<form class="inquiry-form" id="${id}" novalidate><div class="demo-note">Демонстрационная форма: заявки пока не отправляются. Можно проверить заполнение и выбранный контекст.</div><div class="selection-context"></div><div class="form-grid"><div><label for="${id}-name">Ваше имя</label><input id="${id}-name" name="name" autocomplete="given-name" placeholder="Как к вам обращаться" required minlength="2" maxlength="80"></div><div><label for="${id}-phone">Телефон</label><input id="${id}-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="+7 (___) ___-__-__" required maxlength="24"></div></div><details class="optional-message"><summary>Что вы планируете? <span>Необязательно</span></summary><label class="sr-only" for="${id}-message">Пожелания к проекту</label><textarea id="${id}-message" name="message" placeholder="Планировка, пожелания или удобное время для встречи" maxlength="2000"></textarea></details><label class="consent"><input type="checkbox" name="consent"><span>Согласие на обработку данных — после добавления <button type="button" data-privacy>согласованной политики</button>. В демоверсии данные не передаются.</span></label><button type="submit" class="button">Проверить заявку <span>↗</span></button><p class="form-note">После подключения приёма заявок свяжемся с вами, чтобы уточнить детали проекта.</p><div class="form-result" role="status" aria-live="polite"></div></form>`}
$('#inline-form').innerHTML=formMarkup('contact-form');$('#modal-form').innerHTML=formMarkup('dialog-form');
function syncContext(){const model=models.find(x=>x.id===state.model);const mood=moods[state.mood];$$('.selection-context').forEach(el=>{el.classList.toggle('active',!!model||!!mood||!!state.interest);el.innerHTML=`<div><strong>Ваш выбор</strong><button type="button" data-clear>Очистить</button></div>${model?`<p>Коллекция: ${model.name} · <button type="button" data-return-model="${model.id}">Посмотреть</button></p>`:''}${mood?`<p>Направление: ${mood.label}</p>`:''}${state.interest?'<p>Кухня с техникой</p>':''}`})}
function openForm(type,source,interest){$$('dialog[open]').forEach(d=>d.close());state.type=type;state.source=source||'contact';state.interest=interest||null;if(source==='materials'&&!state.mood)state.mood='light';$('#inquiry-title').textContent=({showroom:'Встретимся в шоуруме',designer:'Обсудим совместный проект',question:'Обсудим ваш вопрос',estimate:'Давайте обсудим вашу кухню'})[type]||'Давайте обсудим вашу кухню';const details=$('#dialog-form .optional-message');details.querySelector('summary').innerHTML=type==='showroom'?'Пожелание по дню и времени <span>Необязательно</span>':type==='question'?'Ваш вопрос <span>Необязательно</span>':'Что вы планируете? <span>Необязательно</span>';if(type==='question'||type==='designer')details.open=true;$('#dialog-form .form-result').textContent='';syncContext();showDialog($('#inquiry'));}
function openPrivacy(){const p=$('#privacy');showDialog(p)}
$('#privacy').addEventListener('close',()=>{if($('dialog[open]'))document.body.classList.add('modal-open')});
function handleSubmit(e){e.preventDefault();const form=e.target;const name=form.elements.name,phone=form.elements.phone;name.setCustomValidity(name.value.trim().length<2?'Введите имя — не менее двух символов.':'');const digits=phone.value.replace(/\D/g,'');phone.setCustomValidity(digits.length<10||digits.length>15?'Введите телефон: от 10 до 15 цифр.':'');if(!form.reportValidity())return;const result=form.querySelector('.form-result');result.replaceChildren();const strong=document.createElement('strong');strong.textContent='Форма заполнена. Заявка не отправлена.';result.append(strong);const text=document.createElement('p');text.textContent='Приём обращений будет доступен после подключения салона и добавления согласованной политики. Имя и телефон не сохранены на сервере.';result.append(text);}
$$('.inquiry-form').forEach(f=>{f.onsubmit=handleSubmit;f.addEventListener('input',e=>{if(e.target.setCustomValidity)e.target.setCustomValidity('');f.querySelector('.form-result').textContent=''})});
document.addEventListener('click',e=>{const model=e.target.closest('[data-model]');if(model)openGallery(model.dataset.model,model);const form=e.target.closest('[data-form]');if(form)openForm(form.dataset.form,form.dataset.source,form.dataset.interest);const estimate=e.target.closest('[data-gallery-estimate]');if(estimate){state.model=estimate.dataset.galleryEstimate;openForm('estimate','collection')};const thumb=e.target.closest('[data-gallery-src]');if(thumb)swapImage($('.gallery-image'),thumb.dataset.gallerySrc,$('#gallery-status')).then(ok=>{if(ok)$$('[data-gallery-src]').forEach(b=>b.setAttribute('aria-pressed',String(b===thumb)))});const mood=e.target.closest('[data-mood]');if(mood)selectMood(mood.dataset.mood);if(e.target.closest('[data-clear]')){state.model=null;state.mood=null;state.interest=null;syncContext()};const back=e.target.closest('[data-return-model]');if(back){$('#inquiry').close();openGallery(back.dataset.returnModel)}if(e.target.closest('[data-privacy]')||e.target.closest('#privacy-open'))openPrivacy()});
const contactObserver=new IntersectionObserver(entries=>{$('.mobile-bottom').classList.toggle('hidden',entries[0].isIntersecting)},{threshold:.1});contactObserver.observe($('#contact'));
if(document.modelContext?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'select_kitchen_mood',title:'Выбрать направление кухни',description:'Выбрать визуальное направление и обновить изображение и контекст формы. Не отправляет заявку.',inputSchema:{type:'object',properties:{mood:{type:'string',enum:['light','warm','contrast']}},required:['mood'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='mood')||!Object.hasOwn(moods,input.mood))throw Error('Invalid mood');return selectMood(input.mood)}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
