import {getShowroomConfig} from './config.js';
import {ImageViewAdapter} from './image-view-adapter.js';

const mobile=()=>matchMedia('(max-width:700px)').matches;
const coord=(position)=>position?.[mobile()?'mobile':'desktop']||position?.desktop||position;
let stylesPromise;
function loadStyles(){if(stylesPromise)return stylesPromise;stylesPromise=new Promise((resolve,reject)=>{const link=document.createElement('link');link.rel='stylesheet';link.href='showroom/showroom.css?v=20261008-spatial';link.onload=resolve;link.onerror=()=>{stylesPromise=null;reject(new Error('Showroom styles unavailable'))};document.head.append(link)});return stylesPromise}
export async function mountShowroom({host,modelId,analytics,onClose}){
 const config=getShowroomConfig(modelId);await loadStyles();
 const controller=new AbortController(),signal=controller.signal;
 const previousOverflow=document.body.style.overflow,previousScroll=scrollY;
 let current=config.viewpoints[0],adapter,detail=null,busy=false,closed=false,hintVisible=sessionStorage.getItem('showroom-hint-seen')!=='1',preloadTimer=null,inertiaFrame=0;
 host.hidden=false;host.style.visibility='hidden';
 host.innerHTML=`<div class="sr-shell" aria-label="Интерактивный шоурум ${config.title}">
  <div class="sr-top"><button class="sr-back" type="button" data-close-showroom aria-label="Закрыть шоурум">← <span>Назад к кухне</span></button><div><span class="sr-top-kicker">ИНТЕРАКТИВНЫЙ ШОУРУМ</span><strong>${config.title}</strong></div><button class="sr-x" type="button" data-close-showroom aria-label="Закрыть шоурум">×</button></div>
  <div class="sr-stage" tabindex="0" aria-label="Осмотр кухни"><div class="sr-images"></div><div class="sr-points" aria-label="Детали и направления"></div><div class="sr-hint">Проведите, чтобы осмотреть</div><div class="sr-position" aria-live="polite"></div></div>
  <div class="sr-footer"><span class="sr-footer-caption">Подготовленные ракурсы кухни</span><div class="sr-step-list" aria-label="Ракурсы кухни"></div></div>
  <div class="sr-detail" hidden></div>
 </div>`;
 const shell=host.querySelector('.sr-shell'),stage=host.querySelector('.sr-stage'),points=host.querySelector('.sr-points'),position=host.querySelector('.sr-position'),steps=host.querySelector('.sr-step-list'),detailNode=host.querySelector('.sr-detail'),hint=host.querySelector('.sr-hint');
 adapter=new ImageViewAdapter(stage);
 function event(name,extra={}){analytics(name,{kitchen_id:modelId,viewpoint_id:current.id,...extra})}
 function hideHint(){if(!hintVisible)return;hintVisible=false;hint.hidden=true;sessionStorage.setItem('showroom-hint-seen','1')}
 function closeDetail(){if(!detail)return;const old=detail;detail=null;detailNode.hidden=true;detailNode.replaceChildren();shell.classList.remove('sr-detail-open');event('showroom_detail_close',{hotspot_id:old.id,category:old.category});stage.focus({preventScroll:true})}
 function openDetail(hotspot){hideHint();detail=hotspot;event('showroom_hotspot_click',{hotspot_id:hotspot.id,category:hotspot.category});event('showroom_detail_open',{hotspot_id:hotspot.id,category:hotspot.category});const specs=(hotspot.specs||[]).map(s=>`<div><dt>${s.label}</dt><dd>${s.value}</dd></div>`).join('');detailNode.innerHTML=`<div class="sr-detail-handle" aria-hidden="true"></div><button class="sr-detail-x" type="button" aria-label="Закрыть карточку">×</button><img src="${hotspot.image}" alt="${hotspot.title}" loading="lazy" decoding="async"><div class="sr-detail-copy"><p class="eyebrow">${hotspot.category}</p><h3>${hotspot.title}</h3><p>${hotspot.description}</p>${specs?`<dl>${specs}</dl>`:''}<a class="button" href="#popup1" data-popup="estimate" data-source="mini-showroom">Узнать стоимость <svg class="ui-arrow" viewBox="0 0 32 32" aria-hidden="true"><path d="M6 26 26 6M15 6h11v11"/></svg></a></div>`;detailNode.hidden=false;shell.classList.add('sr-detail-open');detailNode.querySelector('.sr-detail-x').focus({preventScroll:true})}
 function renderControls(){points.replaceChildren();position.textContent=`${String(config.viewpoints.indexOf(current)+1).padStart(2,'0')} / ${String(config.viewpoints.length).padStart(2,'0')} · ${current.title}`;steps.innerHTML=config.viewpoints.map((view,i)=>`<button type="button" data-step="${view.id}" aria-current="${view.id===current.id?'step':'false'}" aria-label="${view.title}"><span>${String(i+1).padStart(2,'0')}</span>${view.title}</button>`).join('');
  for(const [direction,label,arrow] of [[-1,'Осмотреть левее','←'],[1,'Осмотреть правее','→']]){const look=document.createElement('button');look.type='button';look.className=`sr-look sr-look-${direction<0?'left':'right'}`;look.dataset.look=String(direction);look.setAttribute('aria-label',label);look.innerHTML=`<span>${arrow}</span>`;points.append(look)}
  for(const connection of current.connections){const target=config.viewpoints.find(v=>v.id===connection.viewpointId);if(!target)continue;const p=coord(connection.position);const button=document.createElement('button');button.type='button';button.className='sr-move';button.style.left=`${p.x}%`;button.style.top=`${p.y}%`;button.dataset.move=target.id;button.setAttribute('aria-label',`Перейти: ${target.title}`);button.innerHTML=`<span class="sr-move-arrow">${connection.direction==='back'?'↓':connection.direction==='left'?'←':connection.direction==='right'?'→':'↑'}</span><span class="sr-move-label">${target.title}</span>`;points.append(button)}
  for(const hotspot of config.hotspots.filter(h=>h.viewpointId===current.id)){const p=coord(hotspot.position);const button=document.createElement('button');button.type='button';button.className='sr-hotspot';button.style.left=`${p.x}%`;button.style.top=`${p.y}%`;button.dataset.hotspot=hotspot.id;button.setAttribute('aria-label',`Открыть деталь: ${hotspot.title}`);button.innerHTML=`<span class="sr-hotspot-icon">+</span><span class="sr-hotspot-label">${hotspot.title}</span>`;points.append(button)}
 }
 function schedulePreload(){clearTimeout(preloadTimer);const adjacent=current.connections.map(c=>config.viewpoints.find(v=>v.id===c.viewpointId)).filter(Boolean).slice(0,2);preloadTimer=setTimeout(()=>{if(!closed&&navigator.connection?.saveData!==true)adjacent.forEach(v=>adapter.preload(v))},450)}
 async function goTo(id){if(busy||closed||id===current.id)return;const target=config.viewpoints.find(v=>v.id===id);if(!target)return;hideHint();closeDetail();busy=true;shell.classList.add('sr-moving');const direction=current.connections.find(c=>c.viewpointId===id)?.direction||'forward';try{await adapter.transition(target,direction);if(closed)return;current=target;renderControls();event('showroom_viewpoint_change',{direction});schedulePreload()}catch(error){console.error(error);event('showroom_error',{reason:'viewpoint_image'});showSceneError(target)}finally{busy=false;shell.classList.remove('sr-moving')}}
 function showSceneError(target){let box=stage.querySelector('.sr-scene-error');if(box)box.remove();box=document.createElement('div');box.className='sr-scene-error';box.innerHTML=`<p>Не удалось загрузить ракурс.</p><button type="button">Попробовать ещё раз</button>`;box.querySelector('button').addEventListener('click',()=>{box.remove();goTo(target.id)},{once:true,signal});stage.append(box)}
 function close(){if(closed)return;closed=true;event('showroom_close');closeDetail();clearTimeout(preloadTimer);cancelAnimationFrame(inertiaFrame);controller.abort();adapter.destroy();document.body.style.overflow=previousOverflow;host.style.visibility='';host.replaceChildren();onClose();if(mobile())scrollTo({top:previousScroll,behavior:'instant'});document.querySelector('#showroom-open')?.focus({preventScroll:true})}
 host.addEventListener('click',e=>{if(e.target.closest('[data-close-showroom]'))close();const look=e.target.closest('[data-look]');if(look){cancelAnimationFrame(inertiaFrame);adapter.pan(Number(look.dataset.look)*72);hideHint();event('showroom_camera_drag',{method:'button'})}const move=e.target.closest('[data-move]');if(move)goTo(move.dataset.move);const step=e.target.closest('[data-step]');if(step)goTo(step.dataset.step);const hotspotButton=e.target.closest('[data-hotspot]');if(hotspotButton){const hotspot=config.hotspots.find(h=>h.id===hotspotButton.dataset.hotspot);if(hotspot)openDetail(hotspot)}if(e.target.closest('.sr-detail-x'))closeDetail();if(e.target.closest('.sr-detail .button'))event('showroom_cta_click',{hotspot_id:detail?.id,category:detail?.category})},{signal});
 document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(detail)closeDetail();else if(!closed)close()},{signal});
 let pointerX=0,pointerY=0,lastPointerTime=0,dragged=false,dragAxis=null,velocity=0;
 stage.addEventListener('pointerdown',e=>{if(e.target.closest('button')||busy)return;cancelAnimationFrame(inertiaFrame);pointerX=e.clientX;pointerY=e.clientY;lastPointerTime=performance.now();dragged=false;dragAxis=null;velocity=0;stage.setPointerCapture(e.pointerId)},{signal});
 stage.addEventListener('pointermove',e=>{if(!stage.hasPointerCapture(e.pointerId)||busy)return;const dx=e.clientX-pointerX,dy=e.clientY-pointerY;if(!dragAxis&&Math.hypot(dx,dy)>7)dragAxis=Math.abs(dx)>Math.abs(dy)?'x':'y';if(dragAxis==='y'){stage.releasePointerCapture(e.pointerId);return}if(dragAxis==='x'){const now=performance.now(),elapsed=Math.max(8,now-lastPointerTime);dragged=true;adapter.pan(dx*.78);velocity=dx/elapsed*16;pointerX=e.clientX;pointerY=e.clientY;lastPointerTime=now;hideHint()}},{signal});
 stage.addEventListener('pointerup',e=>{if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);if(!dragged)return;hideHint();event('showroom_camera_drag',{method:'gesture'});if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let momentum=velocity;const coast=()=>{momentum*=.9;if(Math.abs(momentum)<.12||closed)return;adapter.pan(momentum);inertiaFrame=requestAnimationFrame(coast)};inertiaFrame=requestAnimationFrame(coast)},{signal});
 let sheetStart=null;detailNode.addEventListener('pointerdown',e=>{if(!mobile()||!e.target.closest('.sr-detail-handle'))return;sheetStart=e.clientY;detailNode.setPointerCapture(e.pointerId)},{signal});detailNode.addEventListener('pointerup',e=>{if(sheetStart===null)return;if(e.clientY-sheetStart>70)closeDetail();sheetStart=null},{signal});
 try{await adapter.showInitial(current)}catch(error){controller.abort();adapter.destroy();host.replaceChildren();host.hidden=true;throw error}
 renderControls();hint.hidden=!hintVisible;host.style.visibility='';if(mobile())document.body.style.overflow='hidden';schedulePreload();host.querySelector('.sr-back').focus({preventScroll:true});
 return {close,destroy:close};
}
